### ISSUE TITLE
无法输入拼音出汉字并进行反查

### ISSUE THREAD

**Issue by tumuyan** [chromezh/rime-kunyomi#2]
示例中这一项是输入拼音出汉字并进行反查，但是我实际使用没有效果
Reverse lookup kunyomi by Chinese pinyin
![demo3](https://github.com/sgalal/rime-kunyomi/raw/master/demo/3.png)

仓库包含了2个方案，其中一个为训读，另一个为スイフトカナ。两个方案都有试过，能实现除上边一个例子外的功能。
请帮忙确认下是什么情况？

**Comment by hihihippp** [comment]
初级安装和使用问题，如何切换到输入法？
➜  ~ uname -a                 
Linux manjaro-virtualbox 5.10.42-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:37:11 UTC 2021 x86_64 GNU/Linux
➜  ~ fcitx5 --version 
5.0.8
安装命令：
➜  ~ rime_frontend=fcitx5-rime bash rime-install sgalal/rime-hanja
➜  ~  ls ~/.local/share/fcitx5/rime/
build                hanja.dict.yaml    kunyomi.dict.yaml    opencc                 sync
hangeul.dict.yaml    hanja.schema.yaml  kunyomi.schema.yaml  swiftkana.dict.yaml    terra_pinyin.userdb
hangeul.schema.yaml  installation.yaml  luna_pinyin.userdb   swiftkana.schema.yaml  user.yaml
请教：如何切换出kunyomi输入方式？

**Comment by sgalal** [comment]
@tumuyan 拼音反查需要依赖 `luna_pinyin`，所以要检查一下有没有 `luna_pinyin` 方案～

**Comment by sgalal** [comment]
@hihihippp 运行 fcitx5 之后在 fcitx5 的设置里切换

**Comment by tumuyan** [comment]
> @tumuyan 拼音反查需要依赖 `luna_pinyin`，所以要检查一下有没有 `luna_pinyin` 方案～

原来如此。谢谢解答
